name: Reusable Workflow
on:
    workflow_call
jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greeting Step
              run: echo "Welcome to Reusable Workflow"